const tokenCheckerResults = {
  TOKEN_NOT_VALID: "TOKEN_NOT_VALID",
  TOKEN_VALID_NO_REMAINING: "TOKEN_VALID_NO_REMAINING",
  TOKEN_VALID_REMAINING: "TOKEN_VALID_REMAINING",
};

export default tokenCheckerResults;